DROP TABLE IF EXISTS ratings;

CREATE TABLE ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    boardgame_id INTEGER NOT NULL,
    rating NUMERIC(3, 1) NOT NULL,
    username VARCHAR(100) NOT NULL,
    CONSTRAINT ratings_value_chk CHECK (rating >= 0 AND rating <= 10)
);

CREATE INDEX idx_ratings_boardgame_id ON ratings(boardgame_id);
CREATE INDEX idx_ratings_username ON ratings(username);
