WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = SIA_ORACLE;

CREATE OR REPLACE VIEW GAMES_V AS
SELECT
    BGG_ID,
    NAME,
    YEAR_PUBLISHED,
    MIN_PLAYERS,
    MAX_PLAYERS,
    AVG_RATING
FROM GAMES;

CREATE OR REPLACE VIEW BOARDGAMES AS
SELECT
    BGG_ID AS BOARDGAME_ID,
    NAME,
    YEAR_PUBLISHED,
    MIN_PLAYERS,
    MAX_PLAYERS,
    AVG_RATING
FROM GAMES;

CREATE OR REPLACE VIEW THEMES_V AS
SELECT
    BGG_ID,
    THEME
FROM THEMES;

CREATE OR REPLACE VIEW USER_RATINGS_V AS
SELECT
    ID,
    BGG_ID,
    RATING,
    USERNAME
FROM USER_RATINGS;

CREATE OR REPLACE VIEW BOARDGAMES_FULL_V AS
SELECT
    g.BGG_ID,
    g.NAME,
    g.YEAR_PUBLISHED,
    g.MIN_PLAYERS,
    g.MAX_PLAYERS,
    g.AVG_RATING,
    t.THEME,
    r.USERNAME,
    r.RATING
FROM GAMES_V g
LEFT JOIN THEMES_V t ON g.BGG_ID = t.BGG_ID
LEFT JOIN USER_RATINGS_V r ON g.BGG_ID = r.BGG_ID;

CREATE OR REPLACE VIEW GAME_RATING_STATS_V AS
SELECT
    g.BGG_ID,
    g.NAME,
    COUNT(r.RATING) AS NUM_RATINGS,
    ROUND(AVG(r.RATING), 2) AS AVG_USER_RATING
FROM GAMES_V g
LEFT JOIN USER_RATINGS_V r ON g.BGG_ID = r.BGG_ID
GROUP BY g.BGG_ID, g.NAME;

CREATE OR REPLACE VIEW THEME_RATING_STATS_V AS
SELECT
    t.THEME,
    COUNT(r.RATING) AS NUM_RATINGS,
    ROUND(AVG(r.RATING), 2) AS AVG_RATING
FROM THEMES_V t
JOIN USER_RATINGS_V r ON t.BGG_ID = r.BGG_ID
GROUP BY t.THEME;

CREATE OR REPLACE VIEW TOP_GAMES_V AS
SELECT
    g.BGG_ID,
    g.NAME,
    COUNT(r.RATING) AS NUM_RATINGS,
    ROUND(AVG(r.RATING), 2) AS AVG_USER_RATING
FROM GAMES_V g
LEFT JOIN USER_RATINGS_V r ON g.BGG_ID = r.BGG_ID
GROUP BY g.BGG_ID, g.NAME
HAVING COUNT(r.RATING) > 0;
