server:
  port: 8091

spring:
  application:
    name: DSA-SQL-JPAService
  datasource:
    url: ${POSTGRES_JDBC_URL:jdbc:postgresql://localhost:55432/sia21}
    username: ${POSTGRES_USER:sia}
    password: ${POSTGRES_PASSWORD:sia}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: ${POSTGRES_FLYWAY_ENABLED:false}

logging:
  level:
    org.datasource.ratings: INFO
