server.port=8092
server.servlet.context-path=/DSA-DOC-XLSService

doc.data.source.games.path=${SIA21_GAMES_CSV:src/main/resources/data/games_small.csv}
doc.data.source.themes.path=${SIA21_THEMES_CSV:src/main/resources/data/themes_small_clean.csv}
